from __future__ import annotations

PAYMENTS_STREAM = "payments"
NOTIFY_STREAM = "notify"

NETWORK_TRC20 = "TRC20"
NETWORK_BEP20 = "BEP20"
NETWORK_POLYGON = "POLYGON"
SUPPORTED_PAYMENT_NETWORKS = (NETWORK_TRC20, NETWORK_BEP20, NETWORK_POLYGON)

DEFAULT_LANGUAGE = "en"

CALLBACK_LANGUAGE_PREFIX = "lang:"
CALLBACK_MAIN_PREFIX = "main:"
CALLBACK_PLAN_PREFIX = "plan:"
CALLBACK_NETWORK_PREFIX = "network:"
CALLBACK_SETTINGS_PREFIX = "settings:"
