from __future__ import annotations

PAYMENTS_STREAM = "payments"
NOTIFY_STREAM = "notify"

NETWORK_TRC20 = "TRC20"
NETWORK_BEP20 = "BEP20"
NETWORK_POLYGON = "POLYGON"
SUPPORTED_NETWORKS = (NETWORK_TRC20, NETWORK_BEP20, NETWORK_POLYGON)

PAYMENT_STATUS_SUBMITTED = "submitted"
PAYMENT_STATUS_APPROVED = "approved"
PAYMENT_STATUS_REJECTED = "rejected"

PRECHECK_PASS = "pass"
PRECHECK_FAIL = "fail"
PRECHECK_UNKNOWN = "unknown"

KILL_SWITCH_GLOBAL_KEY = "kill_switch:global"
KILL_SWITCH_USER_PREFIX = "kill_switch:user:"
